# game
FPS = 144
WINDOW_WIDTH = 1500
WINDOW_HEIGHT = 900
FULL_SCREEN = False

# movement (px / sec)
PLAYER_MAX_HORIZONTAL_SPEED = 500
PLAYER_HORIZONTAL_ACCELERATION = .3 * PLAYER_MAX_HORIZONTAL_SPEED

PLAYER_MAX_VERTICAL_SPEED = 1000
PLAYER_VERTICAL_ACCELERATION = 20
PLAYER_JUMP_SPEED = 600
PLAYER_MAX_JUMP_NUM = 3
