# game
FPS = 144
WINDOW_WIDTH = 1500
WINDOW_HEIGHT = 900
FULL_SCREEN = False

# movement (px / sec)
PLAYER_MAX_HORIZONTAL_SPEED = 500
PLAYER_HORIZONTAL_ACCELERATION = .3 * PLAYER_MAX_HORIZONTAL_SPEED

PLAYER_MAX_VERTICAL_SPEED = 2500
PLAYER_FALL_ACCELERATION = 2000
PLAYER_JUMP_INITIAL_SPEED = 1200
PLAYER_MAX_JUMP_NUM = 3
